function out1 = quatErrdtLeftFunc(in1,in2,in3)
%QUATERRDTLEFTFUNC
%    OUT1 = QUATERRDTLEFTFUNC(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    20-Mar-2019 12:51:45

qRef1__dt_1_ = in3(1,:);
qRef2__dt_1_ = in3(2,:);
qRef3__dt_1_ = in3(3,:);
qRef4__dt_1_ = in3(4,:);
qdrQuat_1__dt_0_ = in1(1,:);
qdrQuat_2__dt_0_ = in1(2,:);
qdrQuat_3__dt_0_ = in1(3,:);
qdrQuat_4__dt_0_ = in1(4,:);
out1 = [-qRef1__dt_1_.*qdrQuat_2__dt_0_+qRef2__dt_1_.*qdrQuat_1__dt_0_-qRef3__dt_1_.*qdrQuat_4__dt_0_+qRef4__dt_1_.*qdrQuat_3__dt_0_;-qRef1__dt_1_.*qdrQuat_3__dt_0_+qRef3__dt_1_.*qdrQuat_1__dt_0_+qRef2__dt_1_.*qdrQuat_4__dt_0_-qRef4__dt_1_.*qdrQuat_2__dt_0_;-qRef1__dt_1_.*qdrQuat_4__dt_0_-qRef2__dt_1_.*qdrQuat_3__dt_0_+qRef3__dt_1_.*qdrQuat_2__dt_0_+qRef4__dt_1_.*qdrQuat_1__dt_0_];
