function out1 = quatErrJacFunc(in1,in2)
%QUATERRJACFUNC
%    OUT1 = QUATERRJACFUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    20-Mar-2019 12:51:45

qRef1__dt_0_ = in2(1,:);
qRef2__dt_0_ = in2(2,:);
qRef3__dt_0_ = in2(3,:);
qRef4__dt_0_ = in2(4,:);
qdrQuat_1__dt_0_ = in1(1,:);
qdrQuat_2__dt_0_ = in1(2,:);
qdrQuat_3__dt_0_ = in1(3,:);
qdrQuat_4__dt_0_ = in1(4,:);
t2 = (qRef1__dt_0_.*qdrQuat_4__dt_0_)./2.0;
t3 = (qRef4__dt_0_.*qdrQuat_1__dt_0_)./2.0;
t4 = (qRef3__dt_0_.*qdrQuat_3__dt_0_)./2.0;
t5 = (qRef4__dt_0_.*qdrQuat_4__dt_0_)./2.0;
t6 = (qRef1__dt_0_.*qdrQuat_2__dt_0_)./2.0;
t7 = (qRef2__dt_0_.*qdrQuat_1__dt_0_)./2.0;
t8 = (qRef2__dt_0_.*qdrQuat_2__dt_0_)./2.0;
out1 = reshape([t4+t5-(qRef1__dt_0_.*qdrQuat_1__dt_0_)./2.0-(qRef2__dt_0_.*qdrQuat_2__dt_0_)./2.0,-t2-t3-(qRef2__dt_0_.*qdrQuat_3__dt_0_)./2.0-(qRef3__dt_0_.*qdrQuat_2__dt_0_)./2.0,(qRef1__dt_0_.*qdrQuat_3__dt_0_)./2.0+(qRef3__dt_0_.*qdrQuat_1__dt_0_)./2.0-(qRef2__dt_0_.*qdrQuat_4__dt_0_)./2.0-(qRef4__dt_0_.*qdrQuat_2__dt_0_)./2.0,t2+t3-(qRef2__dt_0_.*qdrQuat_3__dt_0_)./2.0-(qRef3__dt_0_.*qdrQuat_2__dt_0_)./2.0,-t4+t5+t8-(qRef1__dt_0_.*qdrQuat_1__dt_0_)./2.0,-t6-t7-(qRef3__dt_0_.*qdrQuat_4__dt_0_)./2.0-(qRef4__dt_0_.*qdrQuat_3__dt_0_)./2.0,qRef1__dt_0_.*qdrQuat_3__dt_0_.*(-1.0./2.0)-(qRef3__dt_0_.*qdrQuat_1__dt_0_)./2.0-(qRef2__dt_0_.*qdrQuat_4__dt_0_)./2.0-(qRef4__dt_0_.*qdrQuat_2__dt_0_)./2.0,t6+t7-(qRef3__dt_0_.*qdrQuat_4__dt_0_)./2.0-(qRef4__dt_0_.*qdrQuat_3__dt_0_)./2.0,t4-t5+t8-(qRef1__dt_0_.*qdrQuat_1__dt_0_)./2.0],[3,3]);
