function quatConsJac = yprQuatConsJac(in1,in2)
%YPRQUATCONSJAC
%    QUATCONSJAC = YPRQUATCONSJAC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    08-Sep-2019 13:25:30

b1 = in1(1,:);
b2 = in1(2,:);
b3 = in1(3,:);
b4 = in1(4,:);
q1 = in2(1,:);
q2 = in2(2,:);
q3 = in2(3,:);
t2 = q1./2.0;
t3 = q2./2.0;
t4 = q3./2.0;
t5 = cos(t3);
t6 = cos(t4);
t7 = sin(t2);
t8 = cos(t2);
t9 = sin(t3);
t10 = sin(t4);
t11 = (t6.*t7.*t9)./2.0;
t12 = (t6.*t8.*t9)./2.0;
t13 = (t5.*t7.*t10)./2.0;
t14 = (t5.*t6.*t7)./2.0;
t15 = (t7.*t9.*t10)./2.0;
t16 = (t5.*t6.*t8)./2.0;
t17 = t12+t13;
t18 = (t5.*t8.*t10)./2.0;
t19 = t15+t16;
t20 = (t8.*t9.*t10)./2.0;
t21 = t11-t18;
t22 = t14-t20;
t23 = t15-t16;
t24 = t14+t20;
t25 = t12-t13;
t26 = t11+t18;
t27 = b3.*t19;
t28 = b1.*t19;
quatConsJac = reshape([t28-b3.*t17+b4.*(t11-(t5.*t8.*t10)./2.0)+b2.*(t14-(t8.*t9.*t10)./2.0),b2.*t17-b1.*t21+b4.*t19+b3.*t22,-t27-b1.*t17-b2.*t21+b4.*t22,-b1.*t26+b2.*t25-b3.*t24+b4.*t23,-b1.*t23+b2.*t24+b3.*t25-b4.*t26,-b1.*t24-b2.*t23+b3.*t26+b4.*t25,t27-b1.*t17-b2.*t21-b4.*t22,-b2.*t19-b4.*t17+b1.*t22-b3.*t21,t28+b3.*t17+b2.*t22-b4.*t21],[3,3]);
